### ISSUE TITLE
View multiple packages at the same time

### ISSUE THREAD

**Issue by jhonny-oliveira** [hsheth2/ppa-stats#14]
Hi there!

is there any chance we could have included functionality to display the downloads of multiple package at the same time? Let's say, instead of being able to choose a single package in the "Package Name" text box, this box would offer a list of all PPA packages together with a check box to select which of them we would like to display.

By the way, great code! Thank you for continuously supporting it!

Cheers!
Jhonny

**Comment by hsheth2** [comment]
Hey @jhonny-oliveira - thanks for opening the issue. To be perfectly honest, I haven’t been maintaining this super actively - just making sure it stays up. 

If you’re up for writing some code to add this, I’d be happy to review, get it merged, and deploy it.

**Comment by jhonny-oliveira** [comment]
I'm afraid my coding skills are very limited! :-(

Thank you for maintaining this tool!
