### ISSUE TITLE
Shows Failed to download statistics

### ISSUE THREAD

**Issue by archisman-panigrahi** [hsheth2/ppa-stats#23]
![image](https://user-images.githubusercontent.com/3063132/148823311-79360ded-7091-4345-accb-a76e70031e67.png)

I tried some of my PPAs as well as hsheth2/ppa.

**Comment by hsheth2** [comment]
Hi @apandada1 - thanks for raising the issue! I can reproduce it on my end, and will take a deeper look into it soon.

**Comment by hsheth2** [comment]
@apandada1 I've added and deployed this change: https://github.com/hsheth2/ppa-stats/commit/fb443d2a303c324ea7e3e59c6ba32a3fa9b151c1. 

It seems to be working for me, so could you give it a try on your end and let me know if it's working?

**Comment by archisman-panigrahi** [comment]
It works. Thank you for the quick fix. It is such a useful tool.
