### ISSUE TITLE
ppa-stats API output

### ISSUE THREAD

**Issue by jhonny-oliveira** [hsheth2/ppa-stats#61]
Hi!

Would it be possible to add API behavior as an alternative to rendering the full web page. Just output the package data has a json?

I maintain an opensource project where I package software for Ubuntu and my website uses similar logic based on launchpad API to show some basic package statistics. Unfortunately, my code (PHP) is incredibly slow and can no longer retrieve the full stats of packages such as Firefox. This software, doesn't seem to have any issue with it.

If you could add the API output, I would use your website instead and drop my code. I tried to scrape your website, but I didn't find a way to do it without enabling JavaScript (curl for instance).

I already looked at the code to see if I could figure it out, but I'm not a developer and I'm afraid this is far behing my skills.

Naturally, I would make an honorable mention in my website about such integration. :-)

Thank you!
Jhonny Oliveira
https://xtradeb.net

**Comment by hsheth2** [comment]
@jhonny-oliveira I'm not planning on adding an API for this project. The logic that computes the actual download statistics runs in the user's browser, so it's not trivial to make an API for it.

In case you want to replicate that logic, the core of it lives here https://github.com/hsheth2/ppa-stats/blob/main/frontend/src/components/PackageStats.vue#L141-L198
